reference: http://www.objc.io/issue-6/travis-ci.html
before_install:
- brew update
- brew upgrade xctool
language: objective-c
cache: bundler
script:
- xctool test -workspace Example/FFCTemplate.xcworkspace -scheme FFCTemplate -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
